import { MigrationInterface, QueryRunner } from 'typeorm';

export class InitSchema1700000000001 implements MigrationInterface {
  name = 'InitSchema1700000000001';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TYPE role_enum AS ENUM ('ADMIN', 'GESTOR', 'CODER');
    `);

    await queryRunner.query(`
      CREATE TYPE vacancy_status_enum AS ENUM ('OPEN', 'CLOSED');
    `);

    await queryRunner.query(`
      CREATE TYPE vacancy_seniority_enum AS ENUM ('JUNIOR', 'MID', 'SENIOR');
    `);

    await queryRunner.query(`
      CREATE TYPE application_status_enum AS ENUM ('PENDING', 'ACCEPTED', 'REJECTED');
    `);

    await queryRunner.query(`
      CREATE TABLE users (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        full_name VARCHAR(120) NOT NULL,
        email VARCHAR(160) NOT NULL UNIQUE,
        password_hash TEXT NOT NULL,
        role role_enum NOT NULL DEFAULT 'CODER',
        is_active BOOLEAN NOT NULL DEFAULT true,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
      );
    `);

    await queryRunner.query(`
      CREATE INDEX idx_users_role ON users(role);
    `);

    await queryRunner.query(`
      CREATE TABLE vacancies (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title VARCHAR(140) NOT NULL,
        description TEXT NOT NULL,
        company VARCHAR(140) NOT NULL,
        location VARCHAR(140),
        salary_min NUMERIC(12,2),
        salary_max NUMERIC(12,2),
        status vacancy_status_enum NOT NULL DEFAULT 'OPEN',
        seniority vacancy_seniority_enum,
        technologies TEXT[] NOT NULL DEFAULT '{}',
        created_by BIGINT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT fk_vacancy_creator
          FOREIGN KEY (created_by) REFERENCES users(id)
          ON DELETE RESTRICT
      );
    `);

    await queryRunner.query(`
      CREATE INDEX idx_vacancies_status ON vacancies(status);
    `);

    await queryRunner.query(`
      CREATE TABLE applications (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT NOT NULL,
        vacancy_id BIGINT NOT NULL,
        status application_status_enum NOT NULL DEFAULT 'PENDING',
        cover_letter TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT uq_user_vacancy UNIQUE (user_id, vacancy_id),
        CONSTRAINT fk_application_user
          FOREIGN KEY (user_id) REFERENCES users(id)
          ON DELETE CASCADE,
        CONSTRAINT fk_application_vacancy
          FOREIGN KEY (vacancy_id) REFERENCES vacancies(id)
          ON DELETE CASCADE
      );
    `);

    await queryRunner.query(`
      CREATE INDEX idx_applications_status ON applications(status);
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE applications`);
    await queryRunner.query(`DROP TABLE vacancies`);
    await queryRunner.query(`DROP TABLE users`);

    await queryRunner.query(`DROP TYPE application_status_enum`);
    await queryRunner.query(`DROP TYPE vacancy_seniority_enum`);
    await queryRunner.query(`DROP TYPE vacancy_status_enum`);
    await queryRunner.query(`DROP TYPE role_enum`);
  }
}
